### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aurorahyi** [eArmada8/vbuffer_merge_split#2]
Hello, first and foremost, I want to thank you for creating this script and making it public.

Running vb_merge.py in the FrameAnalysis directory gave me the following:
```
C:\MGI 0.44.3\FrameAnalysis-2022-06-10-083632>vb_merge.py
Traceback (most recent call last):
  File "C:\MGI 0.44.3\FrameAnalysis-2022-06-10-083632\vb_merge.py", line 106, in <module>
    merge_vb_file_to_output(indices[i])
  File "C:\MGI 0.44.3\FrameAnalysis-2022-06-10-083632\vb_merge.py", line 58, in merge_vb_file_to_output
    output.append('  AlignedByteOffset: ' + str(offsets[element]) + '\n') #Add the correct offset for each element
IndexError: list index out of range
```
Using Python 3.9.12

A few files from the dump:
[FrameAnalysis-2022-06-10-083632.zip](https://github.com/eArmada8/vbuffer_merge_split/files/8878667/FrameAnalysis-2022-06-10-083632.zip)

I may be doing something wrong, if you could provide any insight it would be highly appreciated.

**Comment by eArmada8** [comment]
Hi, I'm sorry, I don't check this often.  My script would not be able to parse this dump and thus does not support this game, it would have to be forked and rewritten (My script only supports CS3/CS4/Hajimari as far as I know, although I wrote a custom version for Kuro no Kiseki).

I looked at the dump you provided, and I cannot figure out what it is doing with the buffers.  The offsets do not make sense.  I suspect that 3DMigoto is not labeling the offsets correctly.  Also, the vertex buffers holding multiple semantics is an issue.  Even if we can figure out how to get it into Blender, we would still need to figure out how to get it out of Blender and back into the game.  Ultimately a custom branch would need to be developed.  If you want to fork my script and rework the algorithm, I can try to provide some guidance, although I am not a programmer.

**Comment by eArmada8** [comment]
I had some time and tried looking at your dump again, to manually force it into Blender, but the mesh you supplied is actually a pointlist, not a trianglelist.  These are not supported by DSS' plugin, and would be kind of unusual to want to import.  Is this the actual mesh you wanted?

**Comment by eArmada8** [comment]
Closing this issue, due to lack of response and lack of material for me to work with.

**Comment by eArmada8** [comment]
I have added support for complex input slots, which should fix this issue.  Thanks.
#4

In reference to the missing elements / semantics, [I have opened up a new issue on the 3DMigoto repository](https://github.com/bo3b/3Dmigoto/issues/165).
