### ISSUE TITLE
Can't see any of the models after importing into Blender - OPBB

### ISSUE THREAD

**Issue by HazzyDevil** [eArmada8/vbuffer_merge_split#5]
Hey great job with trying to get this limitation sorted. Just tested your scripts on One Piece burning blood. Combines the vertex buffers all ok no issues, gives me an output folder.

I use the blender script from darkstarsword to import from the output folder, sweet no errors here either. But there's nothing shown. 
I've attached what I see in blender as well as the dump folder (excluding .dds files as the size becomes too large)

![image](https://user-images.githubusercontent.com/28854701/209291803-e5524a51-a3b0-44db-af9d-adff98e10c0f.png)
[OPPB Dump.zip](https://github.com/eArmada8/vbuffer_merge_split/files/10293248/OPPB.Dump.zip)

**Comment by eArmada8** [comment]
DarkStarSword's Blender import script is case-sensitive (and it should be).  The game engine is using non-standard semantic names that do not conform to DirectX standard names, so the import script is discarding values it does not understand.

Your frame dump shows:

`element[0]:`
`  SemanticName: Position`

`vb0[0]+000 Position: 0.490971774, 0.0454572365, -0.306140542, 1`

but it needs to be

`element[0]:`
`  SemanticName: POSITION`

`vb0[0]+000 POSITION: 0.490971774, 0.0454572365, -0.306140542, 1`

Same with NORMAL, TEXCOORD, etc.  Here is a list of valid DX11 semantic names:  https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics

I am closing this issue as it is not a problem with my script.  (I do have plans to make some sort of tool to mass-rename semantics eventually.)

**Comment by HazzyDevil** [comment]
Ahh I see, I’ll try and rename them to follow the proper semantics. Thanks for the info!

**Comment by eArmada8** [comment]
I successfully imported the meshes you sent me, so it should work for you (at least for seeing in Blender). Best of luck!

**Comment by HazzyDevil** [comment]
Sweet managed to get it imported, although some of the meshes would fail to import into blender due to 4D issues.

However, what I realised is that the only time these would occur would be when the vertex buffer file had a position's last value as being something close to 1 but not exactly such as 1.00000012, 0.99999994 etc: 
![image](https://user-images.githubusercontent.com/28854701/209543354-b44f6651-86b6-4292-8502-e7668a0708f7.png)

So I just made a script to change these values to be exactly 1 and that seems to allow them to import into blender perfectly. You might know better than me as to why this may be.


The other strange thing I noticed for some meshes is this "BLENDSHAPE_POSITION" element. No idea what this is as it's not an official HLSL Semantic
![image](https://user-images.githubusercontent.com/28854701/209543594-45bf9514-e082-43ca-8eaf-9e263266364c.png)

**Comment by eArmada8** [comment]
Sorry, I have no idea what's going on there. I'm not a programmer by trade, just a hobbyist. I'm glad you got things working though!

**Comment by HazzyDevil** [comment]
All good, here's another finding from the game, based off of the issue you've raised in [bo3b/3Dmigoto#165](https://github.com/bo3b/3Dmigoto/issues/165).

So there doesn't seem to be a vertex buffer being dumped for blendweights/blendindices which as you already know, handle's the weights when sculpting in blender and ultimately allows us to make mods to the mesh.

So for dumping skinning matrices in the d3dx.ini file, I've changed it from vs-cb0 to just vb0. Since quote from DarkStarSword: 
> You can still dump this out via dump=vb2 buf if you think there might actually be something useful there, but generally seeing extra unused vertex buffers and semantics like this is just an artefact of how the game engine has been coded.

And I've noticed that there is data within vb0 that doesn't get dumped.

![image](https://user-images.githubusercontent.com/28854701/209658813-d94d28c7-9042-4e5c-9971-dbe35178fb35.png)

As you can see from the screenshot above, the combined vb0 file (vb0 + vb1) using your script is on the right. And on the left is not something I'm too familiar with, however it does contain some of the data from the right. 

You can ignore Texcoord from the right as that was originally in vb1, so it wont appear in the left. But as you can see, I've colour coded the data. Highlights yellow (Position) and blue (Normal) appear in vb0, however the pink highlight doesn't. So I'm wondering if the pink data here is related to the weights. The data is also there in the buffer file when viewing in HxD.

Any thoughts?

**Comment by eArmada8** [comment]
Looks like tangent, or possibly binormal. It's not weights, which would all be positive and add up to 1. (Also, if it's not in the vb0 dump, that means the data is unused in that draw call by the shaders. You can demonstrate this by changing the numbers, nothing will happen.)

**Comment by HazzyDevil** [comment]
I see, thanks for the info! Do you have discord or something where it’d be easier to talk to you on?

**Comment by eArmada8** [comment]
No, sorry...

**Comment by HazzyDevil** [comment]
Was going to gift you something for your help, but sure…

**Comment by eArmada8** [comment]
Thanks! No need though. Glad I could help.
